server:
    port: 8083
    servlet:
      context-path: /springDataDemo
    #ssl:      #key-store: selfsigned.jks
      #key-password: shashi
      #key-store-password: bhusan     
    
spring:
  application:
    name: spring-data-demo


  datasource:
    url: jdbc:mysql://localhost:3306/localdatabase?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver  jpa:    database: mysql
        hibernate:      ddl-auto: update